
Parameters:

  apiGatewayName:
    Type: String
    Default: my-api
  
  apiGatewayStageName:
    Type: String
    Default: stage
  
  apiGatewayHTTPMethodGet:
    Type: String
    Default: GET
  
  cognitoUserPool:
    Type: String
  
  lambdaFunctionNameGet:
    Type: String
    Default: sample-function-get

  lambdaFunctionNamePost:
    Type: String
    Default: sample-function-post
  
  runtime:
    Type: String
    Default: nodejs12.x
  
  lambdaFunctionVersion:
    Type: String
  
  tableName:
    Type: String
    Default: TableSample
    
Resources:
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/${apiGatewayName}
      RetentionInDays: 90

  ApiGatewaySample:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Example API Gateway
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: !Ref apiGatewayName

  ApiGatewayResourceGetId:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewaySample
      ParentId: !GetAtt 
        - ApiGatewaySample
        - RootResourceId
      PathPart: "{id}"

  ApiGatewayMethodGet:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ApiCognitoAuthorizer
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        RequestParameters:
          integration.request.path.proxy: 'method.request.path.proxy'
        Type: AWS_PROXY
        Uri: !Sub >-
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunctionGet.Arn}/invocations
      RequestParameters:
        method.request.path.proxy: true
      ResourceId: !Ref ApiGatewayResourceGetId
      RestApiId: !Ref ApiGatewaySample
  
  ApiGatewayMethodPost:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ApiCognitoAuthorizer
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        RequestParameters:
          integration.request.path.proxy: 'method.request.path.proxy'
        Type: AWS_PROXY
        Uri: !Sub >-
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunctionPost.Arn}/invocations
      RequestParameters:
        method.request.path.proxy: true
      ResourceId: !GetAtt 
        - ApiGatewaySample
        - RootResourceId
      RestApiId: !Ref ApiGatewaySample

  ApiCognitoAuthorizer:          
    Type: AWS::ApiGateway::Authorizer
    Properties:
      IdentitySource: method.request.header.Authorization
      Name: cognitoAuth
      ProviderARNs: 
        - !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${cognitoUserPool}
      RestApiId: !Ref ApiGatewaySample
      Type: COGNITO_USER_POOLS

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiGatewayMethodGet
    Properties:
      RestApiId: !Ref ApiGatewaySample
      StageName: !Ref apiGatewayStageName
      StageDescription:
        AccessLogSetting: 
          DestinationArn: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/apigateway/${apiGatewayName}:*
          Format: '$context.identity.sourceIp $context.authorizer.claims.sub [$context.requestTime] "$context.httpMethod $context.resourcePath $context.protocol" $context.status $context.requestId $context.awsEndpointRequestId $context.xrayTraceId $context.responseLatency $context.integrationLatency "$context.error.message"'

  ApiGatewayAccountConfig:
    Type: "AWS::ApiGateway::Account"
    Properties:
      CloudWatchRoleArn: !GetAtt "ApiGatewayPushToCloudWatchRole.Arn"

  LambdaFunctionGet:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: mvinibap-lambda-code-source
        S3Key: !Sub my-api-${lambdaFunctionVersion}.zip
      Description: Example Lambda function
      FunctionName: !Ref lambdaFunctionNameGet
      Handler: src/handlers/base-route-get.run
      MemorySize: 128
      Role: !GetAtt LambdaIAMRole.Arn
      Runtime: !Ref runtime
      Environment:
        Variables:
          EV_REGION: !Sub ${AWS::Region}
          LAMBDA_VERSION: !Ref lambdaFunctionVersion

  LambdaFunctionPost:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: mvinibap-lambda-code-source
        S3Key: !Sub my-api-${lambdaFunctionVersion}.zip
      Description: Example Lambda function
      FunctionName: !Ref lambdaFunctionNamePost
      Handler: src/handlers/base-route-post.run
      MemorySize: 128
      Role: !GetAtt LambdaIAMRole.Arn
      Runtime: !Ref runtime
      Environment:
        Variables:
          EV_REGION: !Sub ${AWS::Region}
          LAMBDA_VERSION: !Ref lambdaFunctionVersion

  LambdaApiGatewayInvokeGet:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt LambdaFunctionGet.Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub:
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/*/*/*
        - __ApiId__: !Ref ApiGatewaySample
  
  LambdaApiGatewayInvokePost:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt LambdaFunctionPost.Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub:
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/*/*/*
        - __ApiId__: !Ref ApiGatewaySample

  ApiGatewayPushToCloudWatchRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"

  LambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - dynamodb:*
                Resource:
                  - !Sub arn:aws:dynamodb:*:*:table/${tableName}
                  - !Sub arn:aws:dynamodb:*:*:table/${tableName}/*
              - 
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${lambdaFunctionNameGet}:*
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${lambdaFunctionNamePost}:*
          PolicyName: lambda

  TableSample:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref tableName
      AttributeDefinitions:
        - AttributeName: HashId
          AttributeType: S
        - AttributeName: RangeId
          AttributeType: S
        - AttributeName: IndexSample
          AttributeType: S
      KeySchema:
        - AttributeName: HashId
          KeyType: HASH
        - AttributeName: RangeId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: IndexSampleName
          KeySchema:
            - AttributeName: IndexSample
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
